---
title: "Daily Expenses"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(dplyr)

expenses<-read.csv("dailyexpenses.csv")
expenses$Date <- as.Date(expenses$Date,
                         "%d/%m/%Y")
pc<-read.csv("piechart.csv")
```
# Overall Expenses

## Column {data-width=350}

### Minimum Expense

```{r}
tot <- expenses[,2:9]
total<- colSums(tot)

minvalue <- min(total)
valueBox(minvalue)
```

### Maximum Expense

```{r}
maxvalue <- max(total)
valueBox(maxvalue)
```

## Column {data-width=350}

### Pie Chart of Expenses

```{r}

pie <-  ggplot(pc, aes(x = "", y=amount, fill = factor(expense))) +
  geom_bar(width = 1, stat ="identity")+
  labs(fill="expense",
       x=NULL, y=NULL, title="Pie Chart of expenses")

pie + coord_polar(theta = "y", start = 0)

```

# Comparing Overall Expenses 

## Column {data-width=500}

### Compare Expenses 

```{r}
fd <-expenses[,2] #food column 
a1 <- sum(fd)

groc <-expenses[,3]
a2 <- sum(groc)

med <-expenses[,4]
a3 <- sum(med)

fl <-expenses[,5]
a4 <- sum(fl)

tl <-expenses[,6]
a5 <- sum(tl)

ph <-expenses[,7]
a6 <- sum(ph)

electric <- expenses[,8]
a7 <- sum(electric)

misc <- expenses[,9]
a8 <- sum(misc)

detail <- c("food", "groceries", "medical", "fuel", "toll", "phone", "electricity", "miscellaneous")
total <- c(a1, a2, a3, a4, a5, a6, a7, a8)

df <- data.frame(detail, total)
View(df)

ggplot(data = df, aes(x = detail, y = total))+
  geom_bar(stat = "identity", fill = "purple")+
  labs(x = "Items",
       y = "Expenses",
       title = "Comparing Expenses")
```

## Column {data-width=500}

### Total Expenses

```{r}
cm<-expenses[,2:9] #cumulative data
dt<-expenses[,1]
rs<-rowSums(cm)
dg<-data.frame(dt,rs)
ggplot(data = dg, aes(x = dt, y = rs))+
  geom_line(color = "#00AFBB", size = 2)+
  labs(x = "Date",
       y = "Expenses",
       title = "Total Expenses")
```

# Comparing Medical Expenses

## Column {data-width=500}

### Medical Expenses

```{r}
md <- expenses[,4]
de <- expenses[,1]
dm <- data.frame(de,md)


ggplot(data = dm, aes(x = de, y = md))+
  geom_point(color="blue",size = 4 )+
  labs(x = "Expenses",
       y = "Medical",
       title = "Medical Expenses")
```

## Column {data-width=500}

### Distribution of medical expenses

```{r}
ggplot(expenses, aes(x= Medical)) +
  geom_histogram(binwidth = 5,color="black",fill = "blue")

```
